### ISSUE TITLE
Log file missing in linux openSUSE 12.1

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcncip2toolkit#131]
JIRA issue created by: rcook
Originally opened: 2012-06-27 11:58 AM

Issue body:

Google Code Issue http://code.google.com/p/xcncip2toolkit/issues/detail?id=55

Reported by project member atkins245, Jun 13, 2012

What steps will reproduce the problem?
1. Install <connector>.war file (such as millennium.war)
2. Run Tomcat
3. Check log file in /var/log/tomcat6/ don't see millennium.toolkit.log

What is the expected output? What do you see instead?
  millennium.toolkit.log

Please use labels and text to provide additional information.
  I see the setting here: ../logs/millenniumtoolkit.log (logs has s - but linux log does not have s)

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2012-12-03 05:29 PM

Comment body:

This problem is happening for me too.  Logs are not in the expected directory (/usr/local/apache-tomcat-6.0.32/logs) like they used to be.  No changes have been made to the log4j configuration - it remains the same between 1.1 and 1.2.  This started happening sometime between 1.1 and 1.2.  Now the logs are showing up in /usr/local/logs.  For a brief time it used to write to /usr/local/logs/voyager-1.2toolkit.log, but no longer.  Now my voyager-1.2.war war file sometimes logs to /usr/local/logs/toolkit.log (not voyager-1.2toolkit.log as expected).  Sometimes it creates an empty toolkit.log file in Tomcat Home.  Usually it doesn't log at all.  It's very unpredictable.  In any case, voyager-1.2toolkit.log is no longer being created.  I chatted with John on Skype about this briefly roughly a month ago, he suggested checking my Tomcat startup logs for an indication where the logging is going too.  I can't find anything in the Tomcat logs pertaining to logging.  

John, I'd have to double check with my supervisor but I can probably give you access to my Ubuntu server if you'd like to take a look around.

pzurek@xc-zurek:/usr/local/apache-tomcat-6.0.32$ find / -name "voyager-1.2toolkit.log" 2>/dev/null
pzurek@xc-zurek:/usr/local/logs$ ls -ltr /usr/local/apache-tomcat-6.0.32/webapps/
total 48928
drwxr-xr-x 10 root root     4096 Aug 15  2011 docs
drwxr-xr-x  5 root root     4096 Aug 15  2011 examples
drwxr-xr-x  5 root root     4096 Aug 15  2011 host-manager
-rw-r--r--  1 root root    18282 Jan 18  2012 browser.war
drwxr-xr-x  4 root root     4096 Jan 18  2012 browser
drwxr-xr-x  3 root root     4096 Feb  1  2012 ROOT
drwxr-xr-x  5 root root     4096 Feb  1  2012 manager
-rw-r--r--  1 root root  9396641 Sep  4 21:14 OAIToolkit.war
drwxr-xr-x  7 root root     4096 Sep  4 21:14 OAIToolkit
-rw-r--r--  1 root root  4085655 Sep 13 17:12 solr.war
drwxr-xr-x  6 root root     4096 Sep 21 15:03 solr
drwxr-xr-x  2 root root     4096 Sep 27 19:54 log
-rw-r--r--  1 root root 19971280 Dec  3 15:19 voyager-1.2.war
drwxr-xr-x  5 root root     4096 Dec  3 15:19 voyager-1.2
-rw-r--r--  1 root root 16574359 Dec  3 16:11 voyager-1.1.war
drwxr-xr-x  4 root root     4096 Dec  3 16:11 voyager-1.1

pzurek@xc-zurek:/usr/local/logs$ ls -ltr
total 12684
-rw-r--r-- 1 root root 1050070 Nov 14 13:12 voyager-1.1toolkit.log.2
drwxr-xr-x 3 root root    4096 Nov 16 16:42 solr
drwxr-xr-x 2 root root    4096 Nov 16 16:42 log
-rw-r--r-- 1 root root 1048648 Nov 16 16:42 voyager-1.1toolkit.log.1
-rw-r--r-- 1 root root 1048665 Nov 21 14:34 toolkit.log.10
-rw-r--r-- 1 root root 1048630 Nov 21 15:36 toolkit.log.9
-rw-r--r-- 1 root root 1048631 Nov 21 16:32 toolkit.log.8
-rw-r--r-- 1 root root 1048668 Nov 21 16:47 toolkit.log.7
-rw-r--r-- 1 root root 1048665 Nov 21 17:19 toolkit.log.6
-rw-r--r-- 1 root root 1048663 Nov 23 13:29 toolkit.log.5
-rw-r--r-- 1 root root 1048624 Nov 23 14:14 toolkit.log.4
-rw-r--r-- 1 root root 1048617 Nov 23 14:19 toolkit.log.3
-rw-r--r-- 1 root root 1048667 Nov 23 14:59 toolkit.log.2
-rw-r--r-- 1 root root 1048639 Nov 27 17:10 toolkit.log.1
-rw-r--r-- 1 root root  264739 Dec  3 16:31 voyager-1.1toolkit.log
-rw-r--r-- 1 root root   71560 Dec  3 16:31 toolkit.log

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2012-12-03 05:57 PM

Comment body:

Also, you'll notice that my voyager-1.1.war war file is now logging to /usr/local/logs too instead of the Tomcat logs directory like it used to.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2013-02-20 11:38 AM

Comment body:

Both Patrick and Bach have logs, so moving forward.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2013-05-15 03:32 PM

Comment body:

Below is excerpted from an email thread where we are trying to track down NCIP problems.  I understood the log problem to be one where the logs were written, but to an unexpected location.  But I know understand that they can jump around and sometimes are not being written at all.


-----Original Message-----
From: Zurek, Patrick [mailto:pzurek@uillinois.edu] 
Sent: Wednesday, May 15, 2013 3:38 PM
To: Cook, Randall; Péter Király
Cc: Arbelo, Ralph; bknn0922@gmail.com
Subject: RE: NCIP .132 server

They don't always go to the same location, it's not consistent.  And sometimes they don't show up at all.  Sometimes I can find the log, sometimes I can't.


________________________________________
From: Cook, Randall [rcook@library.rochester.edu]
Sent: Wednesday, May 15, 2013 2:37 PM
To: Zurek, Patrick; Péter Király
Cc: Arbelo, Ralph; bknn0922@gmail.com
Subject: RE: NCIP .132 server

Patrick, but the logs do show up right?  I understood our delay in fixing that issue was that the logs may not go to the expected location, but they do always to a different location, and as long as you know to look for them there that we were fine.

-----Original Message-----
From: Zurek, Patrick [mailto:pzurek@uillinois.edu]
Sent: Wednesday, May 15, 2013 3:35 PM
To: Péter Király; Cook, Randall
Cc: Arbelo, Ralph; bknn0922@gmail.com
Subject: RE: NCIP .132 server

The problem is there's a long running bug that exists in the core that is preventing logging from working correctly.  {sic we know} about it but I don't know what his timeline is for fixing it.  I wish it would be soon because having good log data to look at would be very helpful.  Right now, the logs show up in random places in the filesystem (sometimes in /usr/local/logs, sometimes in the Tomcat log directory, sometimes in the Tomcat root, etc).


notify [~bodfishj] [~admin] [~pzurek] [~pkiraly]

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2013-05-17 10:51 AM

Comment body:

John, I found these messages in catalina.out:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Hope this helps.

**Comment by patrickzurek** [comment]
JIRA Coment by user: bodfishj
JIRA Timestamp: 2013-05-17 10:58 AM

Comment body:

Patrick: Yes, this helps. You should add the following to the Voyager/web/pom.xml and rebuild/redeploy:
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${slf4jVersion}</version>
            <scope>runtime</scope>
        </dependency>
(I suspect this is coming from the 1.2 war.)

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2013-05-17 12:36 PM

Comment body:

Unfortunately, that didn't seem to help.  The .war file is named voyager-1.2b.war, and "find / -name "voyager-1.2btoolkit.log" 2>/dev/null" does not turn up anything.  Also, there's nothing new in the tomcat/logs directory either.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2013-05-17 12:39 PM

Comment body:

Disregard my last comment.  I didn't follow the instructions closely enough, I added the dependency to the core pom, not the Voyager pom.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2013-05-17 01:01 PM

Comment body:

Still no dice.  Nothing new in tomcat/logs nor a file named "voyager-1.2btoolkit.log" on the filesystem.  The only files with updated timestamps in the tomcat/logs directory are:

-bash-3.00$ ls -ltr /usr/local/apache-tomcat-6.0.16/logs
<snip>
-rw-r--r--   1 voyager  endeavor   98698 May 17 13:09 catalina.2013-05-17.log
-rw-r--r--   1 voyager  endeavor 2170829 May 17 13:09 catalina.out
-rw-r--r--   1 voyager  endeavor   48800 May 17 13:10 localhost.2013-05-17.log

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2013-05-17 01:54 PM

Comment body:

John, I found this in logs/catalina.out (not sure how I missed it before, or perhaps it's new after adding the slfj dependency to the Voyager pom).  'voyager-1.2a' is the name of the .war file.  There's also similar messages for the other ncip instances deployed:

Setting ToolkitConfiguration.AppName property to voyager-1.2a.
Setting CoreConfiguration.LoggingDir property to ../logs/, based on servlet container type.
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: ../logs/toolkit.log (No such file or directory)
        at java.io.FileOutputStream.openAppend(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:177)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:102)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
        at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:167)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:132)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:96)
        at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:654)
        at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:612)
        at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:509)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:415)
        at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:349)
        at org.extensiblecatalog.ncip.v2.common.ToolkitServletContextListener.contextInitialized(ToolkitServletContextListener.java:72)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3843)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4350)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:525)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:626)
        at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:553)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:488)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1147)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:311)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:719)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:443)
        at org.apache.catalina.core.StandardService.start(StandardService.java:516)
        at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:578)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:288)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:413)

**Comment by patrickzurek** [comment]
JIRA Coment by user: bodfishj
JIRA Timestamp: 2013-05-17 02:14 PM

Comment body:

Patrick: This is very helpful. I think I understand what's going on with the log. I need to review the code and see what it will take to fix this. First though I think there may be a config setting to get around the problem; I'll post a comment soon on this.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2013-05-17 02:17 PM

Comment body:

Thanks.  Some log messages would be really helpful right about now, especially since I can't attach a debugger to the toolkit at the moment (and I really need to).

**Comment by patrickzurek** [comment]
JIRA Coment by user: bodfishj
JIRA Timestamp: 2013-05-17 02:22 PM

Comment body:

Patrick: Could you try setting the CoreConfiguration.LoggingConfigFile property to the filename you *want* used for the logging file? You could set that in the context descriptor or (if you use one) the toolkit.properties file. That looks to avoid the "smart" (those are air-quotes) behavior that's messing up the log file location.
