### ISSUE TITLE
Receiving error SEVERE: Allocate exception for servlet NCIPServlet java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcncip2toolkit#70]
JIRA issue created by: Patrick Zurek (patrickzurek)
Originally opened: 2012-12-03 04:57 PM

Issue body:

Getting the following error in Tomcat's localhost log whenever I send an NCIP message using the test page:  SEVERE: Allocate exception for servlet NCIPServlet
java.lang.ClassNotFoundException: org.extensiblecatalog.ncip.v2.binding.ncipv2_02.jaxb.dozer.NCIPv2_02JAXBDozerTranslator
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1680)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:169)
        at org.extensiblecatalog.ncip.v2.common.BaseToolkitComponentFactory.createInstance(BaseToolkitComponentFactory.java:198)
        at org.extensiblecatalog.ncip.v2.common.BaseToolkitComponentFactory.getSharedInstance(BaseToolkitComponentFactory.java:164)
        at org.extensiblecatalog.ncip.v2.common.TranslatorFactory.getSharedTranslator(TranslatorFactory.java:50)
        at org.extensiblecatalog.ncip.v2.responder.implprof1.NCIPServlet.init(NCIPServlet.java:224)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1173)
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:809)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:129)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:662)

This happens for LUIS and LookupUser and is repeatable on my Ubuntu server and Rochester's .132 Solaris server.  Test page just hangs at "Sending request to responder ..."

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2012-12-03 04:59 PM

Comment body:

The LUIS message I am using is: 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns1:NCIPMessage xmlns:ns1="http://www.niso.org/2008/ncip" ns1:version="http://www.niso.org/schemas/ncip/v2_0/imp1/xsd/ncip_v2_0.xsd">
<ns1:LookupItemSet>
        <ns1:BibliographicId>
                <ns1:BibliographicRecordId>
                        <ns1:BibliographicRecordIdentifier>21236</ns1:BibliographicRecordIdentifier>
                        <ns1:AgencyId>NRU</ns1:AgencyId>
                </ns1:BibliographicRecordId>
        </ns1:BibliographicId>
</ns1:LookupItemSet>
</ns1:NCIPMessage>

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2012-12-03 05:51 PM

Comment body:

Fixed by adding 
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>binding-ncipv2_02</artifactId>
            <version>${toolkitVersion}</version>
            <scope>compile</scope>
        </dependency>
to my toolkit/web/pom.xml

**Comment by patrickzurek** [comment]
Issue resolved: 2012-12-03 05:51 PM
