### ISSUE TITLE
NCIP 2 work - mismatch between scheme and what the vxws returns (???)

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcncip2toolkit#82]
JIRA issue created by: rcook
Originally opened: 2012-11-12 11:32 AM

Issue body:

This request
I think we have a scheme difference.  Fore example, when something is "Charged" we expect a response that says "Charged" but it looks like webservices are returing something like "Charged - Due on 2012-05-16" but we expect to get the due date from the "Date Due" data element.  There are a lot of "missing" responses from when we hooked our Drupal Toolkit release candidate to an NCIP 2 instance.

Note:  I think this is great, as this is a good way to flush out more problems that might remain with NCIP connectors.

I was using http://128.151.244.132:8080/voyager-1.1/  for NCIP and http://192.17.55.226/xc-full-test/node/2539197/xc/download for Drupal.

 

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns1:NCIPMessage xmlns:ns1="http://www.niso.org/2008/ncip" ns1:version="http://www.niso.org/schemas/ncip/v2_0/imp1/xsd/ncip_v2_0.xsd">
<ns1:Ext>
<ns1:LookupItemSet>
        <ns1:BibliographicId>
                <ns1:BibliographicRecordId>
                        <ns1:BibliographicRecordIdentifier>3554253</ns1:BibliographicRecordIdentifier>
                        <ns1:AgencyId>XC</ns1:AgencyId>
                </ns1:BibliographicRecordId>
        </ns1:BibliographicId>
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Bibliographic Description</ns1:ItemElementType>
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Circulation Status</ns1:ItemElementType>
        
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Electronic Resource</ns1:ItemElementType>
        
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Hold Queue Length</ns1:ItemElementType>
        
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Item Description</ns1:ItemElementType>
        
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Item Use Restriction Type</ns1:ItemElementType>
        
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Location</ns1:ItemElementType>

</ns1:LookupItemSet>
</ns1:Ext>
</ns1:NCIPMessage>

Returns this

<?xml version="1.0" encoding="ISO-8859-1"?>
<ns1:NCIPMessage xmlns:ns1="http://www.niso.org/2008/ncip" ns1:version="http://www.niso.org/schemas/ncip/v2_0/imp1/xsd/ncip_v2_0.xsd">
   <ns1:Problem>
      <ns1:ProblemType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/processingerrortype/generalprocessingerror.scm">Temporary Processing Failure</ns1:ProblemType>
      <ns1:ProblemDetail>Exception:
Service error: INVALID_SCHEME_VALUE. org.extensiblecatalog.ncip.v2.service.ServiceException: No match found for scheme 'http://www.extensiblecatalog.ncip.v2.org/schemes/circulationstatus/xccirculationstatus.scm', value 'Charged - Due on 2012-05-16' in org.extensiblecatalog.ncip.v2.service.CirculationStatus; configuration option for defining values for this class is unset.
	at org.extensiblecatalog.ncip.v2.service.SchemeValuePair.find(SchemeValuePair.java:256)
	at org.extensiblecatalog.ncip.v2.service.CirculationStatus.find(CirculationStatus.java:39)
	at org.extensiblecatalog.ncip.v2.voyager.VoyagerLookupItemSetService.performService(VoyagerLookupItemSetService.java:305)
	at org.extensiblecatalog.ncip.v2.voyager.VoyagerLookupItemSetService.performService(VoyagerLookupItemSetService.java:44)
	at org.extensiblecatalog.ncip.v2.common.MappedMessageHandler.performService(MappedMessageHandler.java:264)
	at org.extensiblecatalog.ncip.v2.responder.implprof1.NCIPServlet.doPost(NCIPServlet.java:244)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:844)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
	at java.lang.Thread.run(Thread.java:619)
</ns1:ProblemDetail>
      <ns1:ProblemElement>NCIPMessage</ns1:ProblemElement>
   </ns1:Problem>
</ns1:NCIPMessage>

notify [~mwesley] [~pkiraly]

**Comment by patrickzurek** [comment]
JIRA Coment by user: pkiraly
JIRA Timestamp: 2012-11-12 03:37 PM

Comment body:

Hi Randall, please let me know exactly how to call NCIP inside DT. Do you use the full record page with NCIP debug on and see the Drupal log, or do you use the "test" tab near the NCIP server. If this is the case, please let us know the verb you call, and the settings on the form in order to repeat your request.

Thanks,
Péter

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2012-11-12 03:42 PM

Comment body:

I use the NCIP Test page on the NCIP Server and the sample xml found http://code.google.com/p/xcncip2toolkit/wiki/lookupItemSet 

[~pkiraly]

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2012-11-12 03:44 PM

Comment body:

but I just did it from in the DT Test pages and got the following, still enough to suggest that there is a scheme incompatibiltiy.  

<ns1:ProblemDetail>Exception: Service error: INVALID_SCHEME_VALUE. org.extensiblecatalog.ncip.v2.service.ServiceException: No match found for scheme 'http://www.extensiblecatalog.ncip.v2.org/schemes/circulationstatus/xccirculationstatus.scm', value 'Charged - Due on 2012-05-16' in org.extensiblecatalog.ncip.v2.service.CirculationStatus; configuration option for defining values for this class is unset. at org.extensiblecatalog.ncip.v2.service.SchemeValuePair.find(SchemeValuePair.java:256) at org.extensiblecatalog.ncip.v2.service.CirculationStatus.find(CirculationStatus.java:39) at org.extensiblecatalog.ncip.v2.voyager.VoyagerLookupItemSetService.performService(VoyagerLookupItemSetService.java:305) at org.extensiblecatalog.ncip.v2.voyager.VoyagerLookupItemSetService.performService(VoyagerLookupItemSetService.java:44) at org.extensiblecatalog.ncip.v2.common.MappedMessageHandler.performService(MappedMessageHandler.java:264) at org.extensiblecatalog.ncip.v2.responder.implprof1.NCIPServlet.doPost(NCIPServlet.java:244) at javax.servlet.http.HttpServlet.service(HttpServlet.java:710) at javax.servlet.http.HttpServlet.service(HttpServlet.java:803) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286) at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:844) at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583) at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447) at java.lang.Thread.run(Thread.java:619)</

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2012-11-12 04:40 PM

Comment body:

There was a bug checking for the sub string 'Charged' in the item status field.  I fixed it and uploaded a new jar.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2012-12-03 06:16 PM

Comment body:

Since the particular bug where the wrong "Charged" string was being returned is fixed I will close this issue.  However, Randall mentioned that 'There are a lot of "missing" responses from when we hooked our Drupal Toolkit release candidate to an NCIP 2 instance.'  Please open a separate JIRA issue for these instances.

**Comment by patrickzurek** [comment]
Issue resolved: 2012-12-03 06:16 PM
