### ISSUE TITLE
Temporary Processing Failure error in LUIS

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcncip2toolkit#83]
JIRA issue created by: Patrick Zurek (patrickzurek)
Originally opened: 2012-11-08 06:25 PM

Issue body:

On the responder test page, getting the response:

<?xml version="1.0" encoding="ISO-8859-1"?>
<ns1:NCIPMessage xmlns:ns1="http://www.niso.org/2008/ncip" ns1:version="http://www.niso.org/ncip/v2_0/imp1/xsd/ncip_v2_0.xsd" xsi:schemaLocation="http://www.niso.org/2008/ncip ncip_v2_0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <ns1:Problem>
      <ns1:ProblemType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/processingerrortype/generalprocessingerror.scm">Temporary Processing Failure</ns1:ProblemType>
      <ns1:ProblemDetail>Exception creating the NCIPInitiationData object from the servlet's input stream.
Stacktrace from NCIP responder:
Service error: INVALID_MESSAGE_FORMAT. org.extensiblecatalog.ncip.v2.service.ServiceException: Exception creating NCIPMessage object from InputStream.
	at org.extensiblecatalog.ncip.v2.binding.jaxb.dozer.BaseJAXBDozerTranslator.createNCIPMessage(BaseJAXBDozerTranslator.java:462)
	at org.extensiblecatalog.ncip.v2.binding.jaxb.dozer.BaseJAXBDozerTranslator.createInitiationData(BaseJAXBDozerTranslator.java:123)
	at org.extensiblecatalog.ncip.v2.responder.implprof1.NCIPServlet.doPost(NCIPServlet.java:288)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:722)
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 20; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'ns1:LookupItemSet'.]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:527)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:224)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:190)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204)
	at org.extensiblecatalog.ncip.v2.binding.jaxb.dozer.BaseJAXBDozerTranslator.createNCIPMessage(BaseJAXBDozerTranslator.java:454)
	... 16 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 20; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'ns1:LookupItemSet'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:449)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3228)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1908)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:737)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:564)
	at com.sun.xml.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.startElement(ValidatingUnmarshaller.java:101)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:150)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:218)
	... 20 more
</ns1:ProblemDetail>
   </ns1:Problem>
</ns1:NCIPMessage>

For message:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns1:NCIPMessage xmlns:ns1="http://www.niso.org/2008/ncip" ns1:version="http://www.niso.org/schemas/ncip/v2_0/imp1/xsd/ncip_v2_0.xsd">
<ns1:Ext>
<ns1:LookupItemSet>
        <ns1:BibliographicId>
                <ns1:BibliographicRecordId>
                        <ns1:BibliographicRecordIdentifier>21236</ns1:BibliographicRecordIdentifier>
                        <ns1:AgencyId>UIUdb</ns1:AgencyId>
                </ns1:BibliographicRecordId>
        </ns1:BibliographicId>
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Bibliographic Description</ns1:ItemElementType>
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Circulation Status</ns1:ItemElementType>
        
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Electronic Resource</ns1:ItemElementType>
        
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Hold Queue Length</ns1:ItemElementType>
        
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Item Description</ns1:ItemElementType>
        
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Item Use Restriction Type</ns1:ItemElementType>
        
        <ns1:ItemElementType ns1:Scheme="http://www.niso.org/ncip/v1_0/schemes/itemelementtype/itemelementtype.scm">Location</ns1:ItemElementType>

</ns1:LookupItemSet>
</ns1:Ext>
</ns1:NCIPMessage>

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2012-11-13 03:57 PM

Comment body:

[~pzurek] can you expound of how this and ncip-150 are related.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2012-11-27 06:13 PM

Comment body:

This can be replicated here:  http://xc-zurek.carli.illinois.edu:8080/voyager-1.2/ using the sample NCIP message I posted above.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2012-12-10 04:08 PM

Comment body:

Status?  I assume this is to be released in 1.2, or not?

**Comment by patrickzurek** [comment]
JIRA Coment by user: bodfishj
JIRA Timestamp: 2012-12-12 09:35 AM

Comment body:

I believe this is fixed; but Patrick will have to re-test.

**Comment by patrickzurek** [comment]
Issue resolved: 2012-12-12 09:35 AM
