### ISSUE TITLE
Core build fails on Ubuntu 10.04, java 1.6.0_26 and maven 3.0.4

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcncip2toolkit#84]
JIRA issue created by: Patrick Zurek (patrickzurek)
Originally opened: 2012-11-07 03:37 PM

Issue body:

Compilation of the core fails on Ubuntu 10.04 using Oracle's Java version 1.6.0_26 and maven version 3.0.4.

pzurek@xc-zurek:~/dev/ncip$ mvn -e install
<snip>
[INFO] Reactor Summary:
[INFO]
[INFO] NCIP 2 Toolkit Root ............................... SUCCESS [1.309s]
[INFO] NCIP V2 Services .................................. SUCCESS [1.742s]
[INFO] NCIP V2 Common .................................... SUCCESS [0.776s]
[INFO] NCIP V2 Binding ................................... SUCCESS [0.049s]
[INFO] NCIP V2 Binding Common Classes .................... FAILURE [0.371s]
[INFO] NCIP V2.01 Binding ................................ SKIPPED
[INFO] NCIP V2 ILS-DI v1 Extensions Binding .............. SKIPPED
[INFO] NCIP V2 WCL v1 Extensions Binding ................. SKIPPED
[INFO] NCIP V2 Responder ................................. SKIPPED
[INFO] NCIP V2 Dummy Parent .............................. SKIPPED
[INFO] NCIP V2 Dummy Services ............................ SKIPPED
[INFO] NCIP V2 Dummy Responder ........................... SKIPPED
[INFO] NCIP V2 Initiator Implementation .................. SKIPPED
[INFO] NCIP V2 Examples .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.663s
[INFO] Finished at: Wed Nov 07 14:35:37 CST 2012
[INFO] Final Memory: 13M/168M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project binding-jar: Compilation failure: Compilation failure:
[ERROR] /home/pzurek/dev/ncip/binding/common/src/main/java/org/extensiblecatalog/ncip/v2/binding/jaxb/NamespaceFilter.java:[133,44] unmappable character for encoding ASCII
[ERROR]
[ERROR] /home/pzurek/dev/ncip/binding/common/src/main/java/org/extensiblecatalog/ncip/v2/binding/jaxb/NamespaceFilter.java:[133,45] unmappable character for encoding ASCII
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project binding-jar: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:516)
        at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:114)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :binding-jar

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2012-11-07 03:50 PM

Comment body:

Adding "<encoding>UTF-8</encoding>" to root pom.xml at:

<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <configuration>
    <encoding>UTF-8</encoding>
  </configuration>
</plugin>

..allows compilation to proceed.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2012-11-07 03:55 PM

Comment body:

Now compilation is failing in one of the tests.  See attached file errors.log for the errors.

Tests in error:
  testToolkitConfigFile(org.extensiblecatalog.ncip.v2.examples.TestToolkitConfig): org.extensiblecatalog.ncip.v2.service.ToolkitException: java.lang.reflect.InvocationTargetException

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] NCIP 2 Toolkit Root ............................... SUCCESS [1.332s]
[INFO] NCIP V2 Services .................................. SUCCESS [1.979s]
[INFO] NCIP V2 Common .................................... SUCCESS [1.003s]
[INFO] NCIP V2 Binding ................................... SUCCESS [0.058s]
[INFO] NCIP V2 Binding Common Classes .................... SUCCESS [0.523s]
[INFO] NCIP V2.01 Binding ................................ SUCCESS [13.139s]
[INFO] NCIP V2 ILS-DI v1 Extensions Binding .............. SUCCESS [10.305s]
[INFO] NCIP V2 WCL v1 Extensions Binding ................. SUCCESS [8.769s]
[INFO] NCIP V2 Responder ................................. SUCCESS [0.241s]
[INFO] NCIP V2 Dummy Parent .............................. SUCCESS [0.034s]
[INFO] NCIP V2 Dummy Services ............................ SUCCESS [0.367s]
[INFO] NCIP V2 Dummy Responder ........................... SUCCESS [1.720s]
[INFO] NCIP V2 Initiator Implementation .................. SUCCESS [0.199s]
[INFO] NCIP V2 Examples .................................. FAILURE [4.771s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.905s
[INFO] Finished at: Wed Nov 07 14:53:14 CST 2012
[INFO] Final Memory: 33M/373M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project examples: There are test failures.
[ERROR]
[ERROR] Please refer to /home/pzurek/dev/ncip/examples/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by patrickzurek** [comment]
JIRA Comment by user: Patrick Zurek (patrickzurek)
JIRA Timestamp: 2012-11-21 04:24 PM

Comment body:

I'm closing this because I can no longer reproduce it.  The toolkit compiles fine in Ubuntu now.

**Comment by patrickzurek** [comment]
Issue resolved: 2012-12-04 10:15 AM
